//
//  SFKeyStoreKey.h
//  SalesforceSecurity
//
//  Created by Kevin Hawkins on 4/28/14.
//  Copyright (c) 2014 salesforce.com. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "SFEncryptionKey.h"

/**
 The type of key that the keystore uses.
 */
typedef NS_ENUM(NSUInteger, SFKeyStoreKeyType) {
    /**
     The key is generated by the key store manager.
     */
    SFKeyStoreKeyTypeGenerated = 0,
    
    /**
     The key is based on the user passcode.
     */
    SFKeyStoreKeyTypePasscode
};

@interface SFKeyStoreKey : NSObject <NSCoding>

- (id)initWithKey:(SFEncryptionKey *)key type:(SFKeyStoreKeyType)keyType;

@property (nonatomic, strong) SFEncryptionKey *encryptionKey;
@property (nonatomic, assign) SFKeyStoreKeyType keyType;

@end
