source("https://rubygems.org")

gem 'fastlane', '~> 2.78'
gem 'xcpretty'
gem 'slather'
gem 'xcov'
gem 'danger'
gem 'danger-xcov'
gem 'danger-junit'
gem 'plist'
gem 'slack-notifier', '~> 2.3', '>= 2.3.2'
gem 'json', '1.8.6'
gem 'nokogiri', '>= 1.8.1'
