source("https://rubygems.org")

gem 'fastlane', '~> 2.78'
gem 'xcpretty'
gem 'slather', '~> 2.4', '>= 2.4.4'
gem 'xcov', '~> 1.3', '>= 1.3.2'
gem 'danger'
gem 'danger-xcov'
gem 'danger-junit'
gem 'plist'
gem 'slack-notifier', '~> 2.3', '>= 2.3.2'
gem 'json', '1.8.6'