name: UI Nightly Tests

on:
  schedule:
    - cron: "0 7 * * 2-6"  # cron is UTC; 11 PM PT every weekday (Mon-Fri).
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ios-ui-test-nightly:
    strategy:
      fail-fast: false
      matrix:
        ios: [^27, ^26, ^18]
        include:
          - ios: ^27
            xcode: ^27
            macos: xcode-27
          - ios: ^26
            xcode: ^26
          - ios: ^18
            xcode: ^16
            macos: macos-15
    uses: ./.github/workflows/reusable-ui-test-workflow.yaml
    permissions:
      contents: read
      pull-requests: write
    with:
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      macos: ${{ matrix.macos }}
      short_timeout: "3"
      long_timeout: "15"
    secrets:
      UI_TEST_CONFIG: ${{ secrets.UI_TEST_CONFIG }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
